/**
 * Array with routes, icons and permissions for menues
 * {
 *  id: number,
 *   idSelected: item selected when select this functionality,
 *   name: label of functionality (label i18n),
 *   iconClass: icon,
 *   routeTo: route to this functionality,
 *   permissions: array with permissions for this funtionality,
 *   isSubMenu: has submenu??
 *   children: array with submenues
 *   weight: item order when list this functionality at the menu list
 * }
 */
export const ListMenuManage = [
  {
    id: 1,
    idSelected: 1,
    name: 'labelDashboard',
    iconClass: 'dashboard',
    routeTo: '/admin/dashboard',
    role: ['TYPE_SUPER_ADMIN', 'TYPE_FLEET_OWNER', 'TYPE_DISPATCHER'],
    permissions: [
      'Guest',
      'AnalyticDailyOrderList',
      'AnalyticSummaryOrderList',
      'AnalyticAverageOrderList',
      'OrderList',
    ],
    isSubMenu: false,
    weight: 1,
  },
  {
    id: 2,
    idSelected: 2,
    name: 'Dispatcher',
    iconClass: 'control',
    routeTo: '/admin/dispatcher',
    role: ['TYPE_SUPER_ADMIN', 'TYPE_DISPATCHER'],
    permissions: ['OrderList'],
    isSubMenu: false,
    weight: 2,
  },
  {
    id: 3,
    idSelected: 3,
    name: 'labelCustomers',
    iconClass: 'team',
    routeTo: '/admin/customer',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['CustomerList'],
    isSubMenu: false,
    weight: 3,
  },
  {
    id: 4,
    idSelected: 3,
    name: '',
    iconClass: 'team',
    routeTo: '/admin/customer/:id?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['CustomerCreate', 'CustomerUpdate'],
    isSubMenu: false,
    weight: 4,
  },
  {
    id: 5,
    idSelected: 5,
    name: 'labelDrivers',
    iconClass: 'idcard',
    routeTo: '/admin/driver',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['DriverList'],
    isSubMenu: false,
    weight: 5,
  },
  {
    id: 6,
    idSelected: 5,
    name: '',
    iconClass: 'idcard',
    routeTo: '/admin/driver/:id?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['DriverCreate', 'DriverUpdate'],
    isSubMenu: false,
    weight: 6,
  },
  {
    id: 7,
    idSelected: 7,
    name: 'labelFleetOwners',
    iconClass: 'solution',
    routeTo: '/admin/fleetowner',
    role: ['TYPE_SUPER_ADMIN', 'TYPE_FLEET_OWNER'],
    permissions: ['FleetOwnerList'],
    isSubMenu: false,
    weight: 7,
  },
  {
    id: 8,
    idSelected: 7,
    name: '',
    iconClass: 'solution',
    routeTo: '/admin/fleetowner/:id?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['FleetOwnerCreate', 'FleetOwnerUpdate'],
    isSubMenu: false,
    weight: 8,
  },
  {
    id: 14,
    idSelected: 14,
    name: 'labelManageSize',
    iconClass: 'arrows-alt',
    routeTo: '/admin/size',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['ProductSizeList'],
    isSubMenu: false,
    weight: 10,
  },
  {
    id: 15,
    idSelected: 14,
    name: '',
    iconClass: 'arrows-alt',
    routeTo: '/admin/size/:id?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['ProductSizeUpdate'],
    isSubMenu: false,
    weight: 10,
  },
  {
    id: 9,
    idSelected: 9,
    name: 'labelSettings',
    iconClass: 'setting',
    routeTo: '',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['SiteSettingUpdate'],
    isSubMenu: true,
    weight: 11,
    children: [
      {
        id: 10,
        idSelected: 10,
        name: 'labelSiteSettings',
        iconClass: 'tool',
        routeTo: '/admin/sitesettings',
        role: ['TYPE_SUPER_ADMIN'],
        permissions: ['SiteSettingUpdate'],
        isSubMenu: true,
        weight: 1,
      },
      {
        id: 11,
        idSelected: 11,
        name: 'labelAccountSettings',
        iconClass: 'profile',
        routeTo: '/admin/accountsettings',
        role: ['TYPE_SUPER_ADMIN'],
        permissions: [
          'AdministratorProfileGet',
          'AdministratorProfileUpdate',
          'FleetOwnerProfileGet',
          'FleetOwnerProfileUpdate',
        ],
        isSubMenu: true,
        weight: 2,
      },
      {
        id: 12,
        idSelected: 12,
        name: 'labelPaymentSettings',
        iconClass: 'credit-card',
        routeTo: '/admin/paymentsettings',
        role: ['TYPE_SUPER_ADMIN'],
        permissions: ['SiteSettingGet', 'SiteSettingUpdate'],
        isSubMenu: true,
        weight: 3,
      },
      {
        id: 13,
        idSelected: 13,
        name: 'labelTaxSettings',
        iconClass: 'calculator',
        routeTo: '/admin/taxsettings',
        role: ['TYPE_SUPER_ADMIN'],
        permissions: ['SettingTaxList'],
        isSubMenu: false,
        weight: 4,
      },
    ],
  },
  {
    id: 16,
    idSelected: 16,
    name: 'labelVehicleTypes',
    iconClass: 'car',
    routeTo: '/admin/vehicletype',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['VehicleTypeList'],
    isSubMenu: false,
    weight: 9,
  },
  {
    id: 17,
    idSelected: 16,
    name: '',
    iconClass: 'car',
    routeTo: '/admin/vehicletype/:id?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['VehicleTypeCreate', 'VehicleTypeUpdate'],
    isSubMenu: false,
    weight: 9,
  },
  {
    id: 20,
    idSelected: 20,
    name: 'labelAccountManagers',
    iconClass: 'user',
    routeTo: '/admin/accountmanager',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['AccountManagerList'],
    isSubMenu: false,
    weight: 8,
  },
  {
    id: 21,
    idSelected: 20,
    name: '',
    iconClass: 'user',
    routeTo: '/admin/accountmanager/:id?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['AccountManagerCreate', 'AccountManagerUpdate'],
    isSubMenu: false,
    weight: 8,
  },
  {
    id: 22,
    idSelected: 20,
    name: '',
    iconClass: 'car',
    routeTo: '/admin/document/:type/:id?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['AccountManagerCreate', 'AccountManagerUpdate'],
    isSubMenu: false,
    weight: 8,
  },
  {
    id: 18,
    idSelected: 18,
    name: '',
    iconClass: 'car',
    routeTo: '/admin/vehicleinsurance',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['VehicleUpdate'],
    isSubMenu: false,
    weight: 9,
  },
  {
    id: 19,
    idSelected: 18,
    name: '',
    iconClass: 'car',
    routeTo: '/admin/vehicleinsurance/:vehicleId?',
    role: ['TYPE_SUPER_ADMIN'],
    permissions: ['VehicleUpdate'],
    isSubMenu: false,
    weight: 9,
  },
  {
    id: 23,
    idSelected: 23,
    name: 'labelPricing',
    iconClass: 'dollar',
    role: ['TYPE_SUPER_ADMIN'],
    routeTo: '/admin/price',
    permissions: ['PriceProductSizeList'],
    isSubMenu: false,
    weight: 10,
  },
  {
    id: 24,
    idSelected: 23,
    name: '',
    iconClass: 'dollar',
    role: ['TYPE_SUPER_ADMIN'],
    routeTo: '/admin/price/:id?',
    permissions: ['PriceProductSizeUpdate'],
    isSubMenu: false,
    weight: 10,
  },
  {
    id: 25,
    idSelected: 2,
    name: '',
    iconClass: 'control',
    role: ['TYPE_SUPER_ADMIN', 'TYPE_DISPATCHER'],
    routeTo: '/admin/dispatcher/:id?',
    permissions: ['OrderGet'],
    isSubMenu: false,
    weight: 2,
  },
  {
    id: 26,
    idSelected: 26,
    name: 'labelStatement',
    iconClass: 'audit',
    role: ['TYPE_SUPER_ADMIN', 'TYPE_FLEET_OWNER'],
    routeTo: '/admin/statement',
    permissions: ['OrderList'],
    isSubMenu: false,
    weight: 10,
  },
  {
    id: 27,
    idSelected: 27,
    name: 'labelTransactions',
    iconClass: 'interaction',
    role: ['TYPE_SUPER_ADMIN', 'TYPE_FLEET_OWNER'],
    routeTo: '/admin/transaction',
    permissions: ['FleetOwnerTransactionList'],
    isSubMenu: false,
    weight: 7,
  },
  {
    id: 100,
    name: '',
    iconClass: 'logout',
    routeTo: '',
    component: '',
    permission: [],
    isSubMenu: false,
    weight: 11,
  },
];
