export enum DocumentVehicleTypeEnum {
  TYPE_VEHICLE_PHOTO = 'TYPE_VEHICLE_PHOTO',
  TYPE_VEHICLE_REGISTRATION_STICKER = 'TYPE_VEHICLE_REGISTRATION_STICKER',
  TYPE_INSURANCE_CERTIFICATE_PICTURE_FILE = 'TYPE_INSURANCE_CERTIFICATE_PICTURE_FILE',
}
