export enum DriverStatusEnum {
  STATUS_ON_BOARDING = 'STATUS_ON_BOARDING',
  STATUS_CLEAR = 'STATUS_CLEAR',
  STATUS_ALERT = 'STATUS_ALERT',
  STATUS_BANNED = 'STATUS_BANNED',
  STATUS_READY = 'STATUS_READY',
}
