export enum TShirtSizeEnum {
  TYPE_SHIRT_SIZE_S = 'TYPE_SHIRT_SIZE_S',
  TYPE_SHIRT_SIZE_M = 'TYPE_SHIRT_SIZE_M',
  TYPE_SHIRT_SIZE_L = 'TYPE_SHIRT_SIZE_L',
  TYPE_SHIRT_SIZE_XL = 'TYPE_SHIRT_SIZE_XL',
  TYPE_SHIRT_SIZE_XXL = 'TYPE_SHIRT_SIZE_XXL',
}
